### ISSUE TITLE
Change the retry schedule config value to also accept a toml array

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#480]
We currently only accept a string, but we should really also accept a toml array (not sure why we didn't do it from the start...).

Example:
```toml
# Should still work
retry_schedule = "5,300,1800,7200,18000,36000,36000"
# Should also work
retry_schedule = [5,300,1800,7200,18000,36000,36000]
```

Reference: https://www.w3schools.io/file/toml-datatypes/#toml-array-type

This will also let us set an empty array and will just cleanup the parsing here.
